### ISSUE TITLE
Music

### ISSUE THREAD

**Issue by kaythaney** [thaneyriordan/Wedding#18]
- [ ] processional song
- [ ] sound system check
- [ ] who's going to run the sound? friend? 
- [ ] what are we doing for music - playlist? 
- [ ] mother/son dance
- [ ] father/daughter dance
- [ ] announcements? 

:musical_keyboard: :notes: :question:

**Comment by riordan** [comment]
Closing in favor of tracking at thaneyriordan/plan#2
