### ISSUE TITLE
Hotel Details

### ISSUE THREAD

**Issue by riordan** [thaneyriordan/Wedding#6]
Once you get the hotel together [thaneyriordan/plan#4], confirm details and re-enable section.
- [x] Confirm Housing Block
- [x] Put Housing Block / Hotel information on page
- [x] Put other options for AirBnB's on page with link to [New York After Rent](http://toe.prx.org/2015/11/new-york-after-rent-post-prop-f-directors-cut/)
- [x] Re-Enable link on Homepage

**Comment by kaythaney** [comment]
amended text on the site (and hotel page), too.
