### ISSUE TITLE
Bridal Party section

### ISSUE THREAD

**Issue by riordan** [thaneyriordan/Wedding#7]
Get headshots and crop em for everyone.

**Comment by riordan** [comment]
@kaythaney: Still worth doing?

**Comment by kaythaney** [comment]
i think we're OK without - possibly just list names of bridal party +
officiant. do we want a special thanks section? (for beck, aleks + ben,
families)?

On Thu, Apr 14, 2016 at 11:10 AM, David Riordan notifications@github.com
wrote:

> @kaythaney https://github.com/kaythaney: Still worth doing?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/thaneyriordan/wedding/issues/7#issuecomment-209991857

## 

@kaythaney http://twitter.com/kaythaney/
@MozillaScience http://twitter.com/mozillascience
